const travelPackages={bali:{title:'Bali Escape',region:'BALI · 4 HARI 3 MALAM',desc:'Pantai, budaya, Ubud dan sunset dalam satu perjalanan santai.',duration:'4 Hari 3 Malam',price:'Rp2.450.000',image:'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1500&q=85',days:['Hari 1 — Arrival & Seminyak','Hari 2 — Ubud & Tegallalang','Hari 3 — Uluwatu & Sunset','Hari 4 — Free time & Departure']},jogja:{title:'Jogja Stories',region:'YOGYAKARTA · 3 HARI 2 MALAM',desc:'Warisan budaya, kuliner dan sudut-sudut kota yang penuh cerita.',duration:'3 Hari 2 Malam',price:'Rp1.850.000',image:'https://images.unsplash.com/photo-1596402184320-417e7178b2cd?auto=format&fit=crop&w=1500&q=85',days:['Hari 1 — Kota & Malioboro','Hari 2 — Borobudur & Kuliner','Hari 3 — Keraton & Departure']},lombok:{title:'Lombok Wild',region:'LOMBOK · 4 HARI 3 MALAM',desc:'Pantai, bukit dan petualangan untuk kamu yang ingin lebih dekat dengan alam.',duration:'4 Hari 3 Malam',price:'Rp2.650.000',image:'https://images.unsplash.com/photo-1539367628448-4bc5c9d171c8?auto=format&fit=crop&w=1500&q=85',days:['Hari 1 — Arrival & Kuta','Hari 2 — Mandalika Coast','Hari 3 — Gili Adventure','Hari 4 — Free time & Departure']}};
const params=new URLSearchParams(location.search),key=params.get('package');
document.querySelectorAll('.book-btn').forEach(b=>b.addEventListener('click',()=>location.href='booking.html?package='+b.dataset.package));
const searchBtn=document.getElementById('searchBtn');if(searchBtn)searchBtn.addEventListener('click',()=>{const p=document.getElementById('searchPackage').value;if(p)location.href='package-detail.html?package='+p;else location.href='packages.html'});
const filter=document.getElementById('filterPackage');if(filter)filter.addEventListener('change',()=>{const v=filter.value.toLowerCase();document.querySelectorAll('.wide-card').forEach(c=>c.style.display=(!v||c.textContent.toLowerCase().includes(v))?'grid':'none')});
const d=travelPackages[key];if(d&&document.getElementById('detailTitle')){document.title=d.title+' — WANDER';document.getElementById('detailTitle').textContent=d.title;document.getElementById('detailRegion').textContent=d.region;document.getElementById('detailDesc').textContent=d.desc;document.getElementById('detailDuration').textContent=d.duration;document.getElementById('detailPrice').textContent=d.price;document.getElementById('detailImg').style.backgroundImage='url("'+d.image+'")';document.getElementById('itinerary').innerHTML=d.days.map((x,i)=>'<div class="it-day"><b>0'+(i+1)+'</b>'+x+'</div>').join('');document.getElementById('bookLink').href='booking.html?package='+key}
const form=document.getElementById('bookingForm');
function makeCode(){let code;do{code='WDR-'+Math.random().toString(36).substring(2,7).toUpperCase()}while(JSON.parse(localStorage.getItem('wander_bookings')||'[]').some(x=>x.code===code));return code}
if(form){if(key&&travelPackages[key])document.getElementById('package').value=travelPackages[key].title;const date=document.getElementById('date');if(date){const t=new Date();t.setDate(t.getDate()+1);date.min=t.toISOString().split('T')[0]}form.addEventListener('submit',e=>{e.preventDefault();const data={code:makeCode(),name:document.getElementById('name').value.trim(),phone:document.getElementById('phone').value.trim(),email:document.getElementById('email')?.value.trim()||'',package:document.getElementById('package').value,origin:document.getElementById('origin').value,guests:Number(document.getElementById('guests').value),date:document.getElementById('date').value,status:'Menunggu konfirmasi',createdAt:new Date().toISOString()};if(!/^08[0-9]{8,13}$/.test(data.phone.replace(/\D/g,''))){document.getElementById('status').textContent='Nomor WhatsApp belum valid. Gunakan format 08xxxxxxxxxx.';return}const all=JSON.parse(localStorage.getItem('wander_bookings')||'[]');all.push(data);localStorage.setItem('wander_bookings',JSON.stringify(all));document.getElementById('status').innerHTML='Booking berhasil dibuat. Kode booking kamu: <strong>'+data.code+'</strong>. Simpan kode ini untuk cek status.';form.reset()})}
const cb=document.getElementById('checkBtn');if(cb)cb.addEventListener('click',()=>{const code=document.getElementById('checkCode').value.trim().toUpperCase(),all=JSON.parse(localStorage.getItem('wander_bookings')||'[]'),b=all.find(x=>x.code===code),r=document.getElementById('checkResult');r.innerHTML=b?'<strong>'+b.code+'</strong><br>'+b.package+' · '+b.guests+' orang · '+b.date+'<br>Status: <b>'+b.status+'</b>':'Booking tidak ditemukan. Periksa kembali kode booking.'});
function renderAdmin(){const rows=document.getElementById('bookingRows');if(!rows)return;const all=JSON.parse(localStorage.getItem('wander_bookings')||'[]');document.getElementById('totalBookings').textContent=all.length;document.getElementById('pendingBookings').textContent=all.filter(x=>x.status==='Menunggu konfirmasi').length;document.getElementById('totalGuests').textContent=all.reduce((a,x)=>a+x.guests,0);rows.innerHTML=all.map(x=>'<tr><td><b>'+x.code+'</b></td><td>'+x.name+'<br><small>'+x.phone+'</small></td><td>'+x.package+'</td><td>'+x.date+'</td><td>'+x.guests+'</td><td>'+x.status+'</td></tr>').join('')||'<tr><td colspan="6">Belum ada booking.</td></tr>'}
renderAdmin();document.getElementById('clearBookings')?.addEventListener('click',()=>{if(confirm('Hapus semua booking di browser ini?')){localStorage.removeItem('wander_bookings');renderAdmin()}});
